trail_mix = {"m&ms" , "peanuts" , "raisins"}
print(trail_mix)
print("cashews" in trail_mix)
print("peanuts" in trail_mix)
trail_mix.add("pretzels")
set = {"peanuts" , "banana chips" , "bits of jerky"}
trail_mix.update(set)
print(trail_mix)
trail_mix.remove("m&ms")
trail_mix.discard("raisins")
trail_mix.discard("rat poison")
print(trail_mix)
nuts = {"peanuts" , "cashews" , "almonds" , "walnuts" , "pecans"}
resulta = trail_mix.union(nuts)
print(resulta)
resultb = trail_mix.intersection(nuts)
print(resultb)
resultc = trail_mix.difference(nuts)
print(resultc)
resultd = nuts.difference(trail_mix)
print(resultd)
